language: node_js

services:
  - docker

before_install:
  - cd udacity-c3-frontend
  - docker build -t wxia61/udacity-frontend .

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wxia61/udacity-frontend