language: node_js

node_js:
   - node # will use latest node

services:
  - docker

before_install:
  - npm install -g --silent @angular/cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd udacity-c3-frontend
  - docker build -t wxia61/udacity-frontend .
  - docker push wxia61/udacity-frontend
  - cd ..
  - cd udacity-c3-restapi-feed
  - docker build -t wxia61/udacity-restapi-feed .
  - docker push wxia61/udacity-restapi-feed
  - cd ..
  - cd udacity-c3-restapi-user
  - docker build -t wxia61/udacity-restapi-user .
  - docker push wxia61/udacity-restapi-user
  - cd ..

script:
  - echo "Done"
